version: 2.1

orbs:
  haskell: haskell-works/haskell-build@2.0.1
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.1.0

workflows:
  multiple-ghcs:
    jobs:
      - haskell/build:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}

      - haskell/build:
          name: GHC 8.6.4
          executor: haskell/ghc-8_6_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}

      - haskell/build:
          name: GHC 7.10.3
          executor: haskell/ghc-7_10_3
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          checkout: true
          requires:
            - GHC 8.4.4
            - GHC 8.6.4
            - GHC 7.10.3
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          filters:
            branches:
              only: master
