version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.0
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.3.0

workflows:
  multiple-ghcs:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          checkout: true
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          filters:
            branches:
              only: master
